var booksData = [
  {
    title: 'Adaptive web-design',
    author: 'Aaron Gustafson',
    language: 'English',
    category: 'education',
    pages: 137,
    description: '"Adaptive Web Design not only provides the clearest, most beautiful explanation of progressive enhancement I\'ve ever read, it\'s also packed full of practical know-how pumped directly into your neocortex through Aaron\'s warm and friendly writing style. If you aren\'t already using progressive enhancement to build websites, you soon will be." --Jeremy Keith, Author, HTML5 for Web Designers"Finally. Progressive enhancement explained with a perfect balance of theory and practice. Aaron\'s take-aways will have you progressively-enhancing your markup, style and behavior with ease." --Dan Cederholm, Author, CSS3 For Web Designers',
    img: '/img/adaptive-web-design.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 1,
    download: '/pdf/Adaptive-Web-Design.pdf'
  },
    {
    title: 'Black Hawk Down',
    author: 'Mark Bowden',
    language: 'English',
    category: 'military roman adventure',
    pages: 420,
    description: 'On October 3, 1993, about a hundred U.S. soldiers were dropped by helicopter into a teeming market in the heart of Mogadishu, Somalia, to abduct two top lieutenants of a Somali warlord. The action was supposed to take an hour. Instead, they spent a long and terrible night fighting thousands of armed Somalis. By morning, eighteen Americans were dead, and more than seventy badly injured. Mark Bowden\'s gripping narrative is one of the most exciting accounts of modern war ever written--a riveting story that captures the heroism, courage and brutality of battle.',
    img: '/img/black-hawk-down.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 2,
    download: '/png/Bowden M. - Black Hawk Down - 1999.png'
  },
    {
    title: 'Drone Warfare',
    author: 'Dave Sloggett',
    language: 'English',
    category: 'military',
    pages: 240,
    description: 'An unmanned aerial vehicle, commonly known as a drone, is an aircraft without a human pilot on board. Its flight is either controlled autonomously by computers in the vehicle, or under the remote control of a navigator or pilot on the ground or in another vehicle. Drone Warfare is one of the first books to examine the development and use of such aerial drones. Drones have been much maligned in the media and popular culture and there has been much controversy over their deployment. This book reveals the history of unmanned aircraft, their recent development, and why they have emerged onto the scene, setting the record straight about drones and their use.',
    img: '/img/droid-wars.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 3
  },
    {
    title: 'How To Hide Anything',
    author: 'Michael Connor',
    language: 'English',
    category: 'military',
    pages: 111,
    description: 'With little effort and expense, you can hide cash, armaments and even family from the menacing eyes of burglars, terrorists or anyone. Learn how to construct dozens of hiding places right in your house and yard. Here are small hiding places for concealing money and jewelry and large places for securing survival supplies or persons. More than 100 drawings show how to turn ordinary items into extraordinary hiding places.',
    img: '/img/how-hide.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 4
  },
    {
    title: 'Swords of the Viking Age',
    author: 'Ian G. Peirce',
    language: 'English',
    category: 'military',
    pages: 160,
    description: 'This new work fills a gap in the literature in English on the swords made and used in northern Europe during the Viking age, between the mid eighth and the mid eleventh centuries. Ewart Oakeshott outlines the significance and diversity of these ancient heirlooms; co-author Ian Peirce, who handled hundreds of swords in his research for this book in museums across northern Europe, selects and describes sixty of the finest representative weapons. Where possible, full-length photographs are included, in addition to illustrations of detail.',
    img: '/img/sword-of-vikingage.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 5
  },
    {
    title: 'Rapid Fire',
    author: 'Anthony G. Williams',
    language: 'English',
    category: 'military',
    pages: 323,
    description: 'This work will be of interest to enthusiasts of the technical aspects of military, naval and aviation history. It provides a comprehensive account of the use of heavy machine guns, automatic cannons and their ammunition, featuring coverage of cartridge design and various projectiles.',
    img: '/img/rapid-fire.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 6
  },
    {
    title: 'The Last Hundred Yards',
    author: 'John Pool',
    language: 'English',
    category: 'military',
    pages: 417,
    description: 'This is the best small unit tactics \'how to\' manual I have read over the past 30 years. The U.S. needs more highly trained Light Infantrymen that possess the skill sets identified in H.J. Poole\'s books.',
    img: '/img/last-houndred-yards.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 7
  },
    {
    title: 'Survival. Fighting Knives',
    author: 'Thompson L.',
    language: 'English',
    category: 'military',
    pages: 95,
    description: 'From the combat-tested, slash-and-thrust blade to me no-nonsense, general-purpose survival knife, this book shows you which type of blade suits your need best. For the man who really uses his knife, it covers utility blades, hollow-handled survival knives, survival kits, folders, combat and streetfighting knives and knife specs and evaluations.',
    img: '/img/survival.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 8
  },
    {
    title: 'Modern Land Combat',
    author: 'David Miller',
    language: 'English',
    category: 'military',
    pages: 208,
    description: 'The technology and tactics of warfare today and the hardware that will rule the battlefields of tomorrow. From the soldier\'s personal weapons to the armored fighting vehicles that form both spearhead and shield.',
    img: '/img/modern-land-combat.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 9
  },
    {
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    language: 'English',
    category: 'adventures fantasy childrens',
    pages: 366,
    description: 'In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.',
    img: '/img/hobbit.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 10
  },
    {
    title: 'Van Helsing',
    author: 'Kevin Ryan',
    language: 'English',
    category: 'adventures fantasy horror',
    pages: 261,
    description: 'Deep in the mountains of nineteenth-century Carpathia lies the mysterious and mythic land of Transylvania, a world where evil is ever-present, where danger rises as the sun sets, and where monsters such as Count Dracula, the Wolf Man, and Frankenstein\'s Monster take form and inhabit man\'s deepest nightmares -- terrifying legends who outlive generations, defying repeated attacks from the doomed brave souls that challenge them in their never-ending war upon the human race. ',
    img: '/img/van-helsing.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 11
  },
    {
    title: 'The Hitchhiker\'s Guide to the Galaxy',
    author: 'Douglas Adams',
    language: 'English',
    category: 'adventures sci-fi humor',
    pages: 224,
    description: 'Seconds before the Earth is demolished to make way for a galactic freeway, Arthur Dent is plucked off the planet by his friend Ford Prefect, a researcher for the revised edition of The Hitchhiker\'s Guide to the Galaxy who, for the last fifteen years, has been posing as an out-of-work actor. \nTogether this dynamic pair begin a journey through space aided by quotes from The Hitchhiker\'s Guide ("A towel is about the most massively useful thing an interstellar hitchhiker can have") and a galaxy-full of fellow travelers: Zaphod Beeblebrox--the two-headed, three-armed ex-hippie and totally out-to-lunch president of the galaxy; Trillian, Zaphod\'s girlfriend (formally Tricia McMillan), whom Arthur tried to pick.',
    img: '/img/galaxy.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 12,
    
  },
    {
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    language: 'English',
    category: 'adventures childrens humor roman historical',
    pages: 311,
    description: 'The most popular pirate story ever written in English, featuring one of literature’s most beloved “bad guys,” Treasure Island has been happily devoured by several generations of boys—and girls—and grownups. Its unforgettable characters include: young Jim Hawkins, who finds himself owner of a map to Treasure Island, where the fabled pirate booty is buried',
    img: '/img/treasure-island.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 13,
    download: '/png/feedbooks_book_97.png'
  },
    {
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    language: 'English',
    category: 'adventures thriller roman historical',
    pages: 490,
    description: 'An ingenious code hidden in the works of Leonardo da Vinci. A desperate race through the cathedrals and castles of Europe. An astonishing truth concealed for centuries . . . unveiled at last. \nWhile in Paris, Harvard symbologist Robert Langdon is awakened by a phone call in the dead of the night. The elderly curator of the Louvre has been murdered inside the museum, his body covered in baffling symbols. As Langdon and gifted French cryptologist Sophie Neveu sort through the bizarre riddles, they are stunned to discover a trail of clues hidden in the works of Leonardo da Vinci—clues visible for all to see and yet ingeniously disguised by the painter.',
    img: '/img/da-vinci.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 14
  },
    {
    title: 'Robinson Crusoe',
    author: 'Daniel Defoe',
    language: 'English',
    category: 'adventures roman historical',
    pages: 320,
    description: 'Robinson Crusoe, set ashore on an island after a terrible storm at sea, is forced to make do with only a knife, some tobacco, and a pipe. He learns how to build a canoe, make bread, and endure endless solitude. That is, until, twenty-four years later, when he confronts another human being.',
    img: '/img/robinson-crusoe.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 15
  },
    {
    title: 'Harry Potter and the Sorcerer\'s Stone',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 310,
    description: 'Harry Potter thinks he is an ordinary boy. He lives with his Uncle Vernon, Aunt Petunia and cousin Dudley, who are mean to him and make him sleep in a cupboard under the stairs. (Dudley, however, has two bedrooms, one to sleep in and one for all his toys and games.) Then Harry starts receiving mysterious letters and his life is changed forever. He is whisked away by a beetle-eyed giant of a man and enrolled at Hogwarts School of Witchcraft and Wizardry. The reason: Harry Potter is a wizard! The first book in the "Harry Potter" series makes the perfect introduction to the world of Hogwarts.',
    img: '/img/harry-potter-1.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 16
  },
    {
    title: 'Harry Potter and the Chamber of Secrets',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 341,
    description: 'All Harry Potter wants is to get away from the Dursleys and go back to Hogwarts School for Witchcraft and Wizardry. But just as he\'s packing his bags, Harry receives a warning from a strange, impish creature named Dobby - who says that if Harry Potter returns to Hogwarts, disaster will strike.\nAnd strike it does. For in Harry\'s second year at Hogwarts, fresh torments and horrors arise, including an outrageously stuck-up new professor, Gilderoy Lockheart, a spirit named Moaning Myrtle who haunts the girls\' bathroom, and the unwanted attentions of Ron Weasley\'s younger sister, Ginny.',
    img: '/img/harry-potter-2.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 17
  },
    {
    title: 'Harry Potter and the Prisoner of Azkaban',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 435,
    description: 'Harry Potter is lucky to reach the age of thirteen, since he has already survived the murderous attacks of the feared Dark Lord on more than one occasion. But his hopes for a quiet term concentrating on Quidditch are dashed when a maniacal mass-murderer escapes from Azkaban, pursued by the soul-sucking Dementors who guard the prison. It\'s assumed that Hogwarts is the safest place for Harry to be. But is it a coincidence that he can feel eyes watching him in the dark, and should he be taking Professor Trelawney\'s ghoulish predictions seriously?',
    img: '/img/harry-potter-3.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 18
  },
    {
    title: 'Harry Potter and the Goblet of Fire',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 734,
    description: 'The summer holidays are dragging on and Harry Potter can\'t wait for the start of the school year. It is his fourth year at Hogwarts School of Witchcraft and Wizardry and there are spells to be learnt and (unluckily) Potions and Divination lessons to be attended. But Harry can\'t know that the atmosphere is darkening around him, and his worst enemy is preparing a fate that it seems will be inescapable ...With characteristic wit, fast-paced humour and marvellous emotional depth, J.K. Rowling has proved herself yet again to be a master story-teller',
    img: '/img/harry-potter-4.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 19
  },
    {
    title: 'Harry Potter and the Half-Blood Prince',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 652,
    description: 'It is the middle of the summer, but there is an unseasonal mist pressing against the windowpanes. Harry Potter is waiting nervously in his bedroom at the Dursleys\' house in Privet Drive for a visit from Professor Dumbledore himself. One of the last times he saw the Headmaster was in a fierce one-to-one duel with Lord Voldemort, and Harry can\'t quite believe that Professor Dumbledore will actually appear at the Dursleys\' of all places. Why is the Professor coming to visit him now? What is it that cannot wait until Harry returns to Hogwarts in a few weeks\' time? Harry\'s sixth year at Hogwarts has already got off to an unusual start, as the worlds of Muggle and magic start to intertwine...',
    img: '/img/harry-potter-6.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 20
  },
    {
    title: 'Harry Potter and the Order of the Phoenix',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 870,
    description: 'Harry Potter is due to start his fifth year at Hogwarts School of Witchcraft and Wizardry. His best friends Ron and Hermione have been very secretive all summer and he is desperate to get back to school and find out what has been going on. However, what Harry discovers is far more devastating than he could ever have expected...\nSuspense, secrets and thrilling action from the pen of J.K. Rowling ensure an electrifying adventure that is impossible to put down.',
    img: '/img/harry-potter-5.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 21
  },
    {
    title: 'Harry Potter and the Deathly Hallows',
    author: 'J.K. Rowling',
    language: 'English',
    category: 'adventures childrens fantasy',
    pages: 759,
    description: 'Harry is waiting in Privet Drive. The Order of the Phoenix is coming to escort him safely away without Voldemort and his supporters knowing - if they can. But what will Harry do then? How can he fulfil the momentous and seemingly impossible task that Professor Dumbledore has left him?',
    img: '/img/harry-potter-7.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 22
  },
    {
    title: 'Around the World in Eighty Days',
    author: 'Jules Verne',
    language: 'English',
    category: 'adventures roman',
    pages: 252,
    description: 'One ill-fated evening at the Reform Club, Phileas Fogg rashly bets his companions £20,000 that he can travel around the entire globe in just eighty days - and he is determined not to lose. Breaking the well-establised routine of his daily life, the reserved Englishman immediately sets off for Dover, accompanied by his hot-blooded French manservant Passepartout. Travelling by train, steamship, sailing boat, sledge and even elephant, they must overcome storms, kidnappings, natural disasters, Sioux attacks and the dogged Inspector Fix of Scotland Yard - who believes that Fogg has robbed the Bank of England - to win the extraordinary wager.',
    img: '/img/80-days.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 23
  },
    {
    title: 'Twenty Thousand Leagues Under the Sea',
    author: 'Jules Verne',
    language: 'English',
    category: 'adventures roman',
    pages: 394,
    description: 'French naturalist Dr. Aronnax embarks on an expedition to hunt down a sea monster, only to discover instead the Nautilus, a remarkable submarine built by the enigmatic Captain Nemo. Together Nemo and Aronnax explore the underwater marvels, undergo a transcendent experience amongst the ruins of Atlantis, and plant a black flag at the South Pole. But Nemo\'s mission is one of revenge-and his methods coldly efficient.',
    img: '/img/2000-leagues.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 24
  },
    {
    title: 'Eragon',
    author: 'Christopher Paolini',
    language: 'English',
    category: 'adventures fantasy',
    pages: 503,
    description: 'When Eragon finds a polished blue stone in the forest, he thinks it is the lucky discovery of a poor farm boy; perhaps it will buy his family meat for the winter. But when the stone brings a dragon hatchling, Eragon soon realizes he has stumbled upon a legacy nearly as old as the Empire itself.\nOvernight his simple life is shattered, and he is thrust into a perilous new world of destiny, magic, and power. With only an ancient sword and the advice of an old storyteller for guidance, Eragon and the fledgling dragon must navigate the dangerous terrain and dark enemies of an Empire ruled by a king whose evil knows no bounds.',
    img: '/img/eragon.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 25
  },
    {
    title: 'The Fellowship of the Ring',
    author: 'J.R.R. Tolkien',
    language: 'English',
    category: 'adventures fantasy',
    pages: 398,
    description: 'Frodo Baggins knew the Ringwraiths were searching for him - and the Ring of Power he bore that would enable Sauron to destroy all that was good in Middle-earth. Now it was up to Frodo and his faithful servant Sam to carry the Ring to where it could be detroyed - in the very center of Sauron\'s dark kingdom.',
    img: '/img/lotr-1.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 26
  },
    {
    title: 'The Two Towers',
    author: 'J.R.R. Tolkien',
    language: 'English',
    category: 'adventures fantasy',
    pages: 322,
    description: 'The Fellowship was scattered. Some were bracing hopelessly for war against the ancient evil of Sauron. Some were contending with the treachery of the wizard Saruman. Only Frodo and Sam were left to take the accursed Ring of Power to be destroyed in Mordor–the dark Kingdom where Sauron was supreme. Their guide was Gollum, deceitful and lust-filled, slave to the corruption of the Ring. Thus continues the magnificent, bestselling tale of adventure begun in The Fellowship of the Ring, which reaches its soul-stirring climax in The Return of the King.',
    img: '/img/lotr-2.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 27
  },
    {
    title: 'The Return of the King',
    author: 'J.R.R. Tolkien',
    language: 'English',
    category: 'adventures fantasy',
    pages: 490,
    description: 'Concluding the story begun in The Hobbit, this is the final part of Tolkien\'s epic masterpiece, The Lord of the Rings.\nThe armies of the Dark Lord are massing as his evil shadow spreads ever wider. Men, Dwarves, Elves and Ents unite forces to do battle agains the Dark. Meanwhile, Frodo and Sam struggle further into Mordor in their heroic quest to destroy the One Ring.',
    img: '/img/lotr-3.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 28
  },
    {
    title: 'The Nurses',
    author: 'Alexandra Robbins',
    language: 'English',
    category: 'medicine drama',
    pages: 368,
    description: 'In this lively, fast-paced narrative, New York Times bestselling author Alexandra Robbins digs deep into the subculture of nursing, drawing readers into a brilliantly captivating in-depth investigation of the extraordinary working lives of nurses and the shocking behind-the-scenes secrets that all patients and their loved ones need to know.',
    img: '/img/the-nurses.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 29
  },
    {
    title: 'MEDICAL INDUSTRIAL COMPLEX',
    author: 'James Morcan',
    language: 'English',
    category: 'medicine',
    pages: 368,
    description: 'Written by novelists, filmmakers and independent researchers James Morcan & Lance Morcan, with a foreword by retired pharmacist Denis Toovey (author of Better Health for You: An Insider\'s Big Picture Guide), this explosive book explores the contention that Big Pharma and other participants in the healthcare sector put profits ahead of patients’ wellbeing and dollars ahead of lives. ',
    img: '/img/medical-industrial.png',
    url: 'http://sachagreif.com/introducing-telescope/',
    id: 30
  }
];
Template.booksList.helpers({
  books: booksData
});